-- Elson Seed Data: 20 trilingual phrase groups (EN/FR/AR)

INSERT INTO phrases (source_text, source_lang, hassaniya_reference, origin, category, difficulty) VALUES
('The sun rises in the east and sets in the west.', 'en', 'f0001', 'flores-200', 'general', 1),
('Le soleil se leve a l''est et se couche a l''ouest.', 'fr', 'f0001', 'flores-200', 'general', 1),
('تشرق الشمس من الشرق وتغرب في الغرب.', 'ar', 'f0001', 'flores-200', 'general', 1),
('Water is essential for all forms of life on Earth.', 'en', 'f0002', 'flores-200', 'science', 1),
('L''eau est essentielle a toutes les formes de vie sur Terre.', 'fr', 'f0002', 'flores-200', 'science', 1),
('الماء ضروري لجميع أشكال الحياة على الأرض.', 'ar', 'f0002', 'flores-200', 'science', 1),
('Education is the most powerful weapon to change the world.', 'en', 'f0003', 'flores-200', 'education', 2),
('L''education est l''arme la plus puissante pour changer le monde.', 'fr', 'f0003', 'flores-200', 'education', 2),
('التعليم هو أقوى سلاح يمكنك استخدامه لتغيير العالم.', 'ar', 'f0003', 'flores-200', 'education', 2),
('The doctor examined the patient carefully before prescribing medicine.', 'en', 'f0004', 'flores-200', 'health', 2),
('Le medecin a examine le patient attentivement avant de prescrire le medicament.', 'fr', 'f0004', 'flores-200', 'health', 2),
('فحص الطبيب المريض بعناية قبل وصف الدواء.', 'ar', 'f0004', 'flores-200', 'health', 2),
('The children played happily in the garden while their parents prepared dinner.', 'en', 'f0005', 'flores-200', 'daily_life', 1),
('Les enfants jouaient joyeusement dans le jardin pendant que leurs parents preparaient le diner.', 'fr', 'f0005', 'flores-200', 'daily_life', 1),
('لعب الأطفال بسعادة في الحديقة بينما كان آباؤهم يعدون العشاء.', 'ar', 'f0005', 'flores-200', 'daily_life', 1),
('The government announced new economic reforms to reduce poverty.', 'en', 'f0006', 'flores-200', 'politics', 2),
('Le gouvernement a annonce de nouvelles reformes economiques pour reduire la pauvrete.', 'fr', 'f0006', 'flores-200', 'politics', 2),
('أعلنت الحكومة عن إصلاحات اقتصادية جديدة للحد من الفقر والبطالة.', 'ar', 'f0006', 'flores-200', 'politics', 2),
('Traditional music and dance are important parts of our cultural heritage.', 'en', 'f0007', 'flores-200', 'culture', 1),
('La musique et la danse traditionnelles sont des elements importants de notre patrimoine culturel.', 'fr', 'f0007', 'flores-200', 'culture', 1),
('الموسيقى والرقص التقليديان جزءان مهمان من تراثنا الثقافي.', 'ar', 'f0007', 'flores-200', 'culture', 1),
('Climate change poses a serious threat to biodiversity around the world.', 'en', 'f0008', 'flores-200', 'environment', 3),
('Le changement climatique constitue une menace serieuse pour la biodiversite dans le monde.', 'fr', 'f0008', 'flores-200', 'environment', 3),
('يشكل تغير المناخ تهديداً خطيراً للتنوع البيولوجي في جميع أنحاء العالم.', 'ar', 'f0008', 'flores-200', 'environment', 3),
('The market was full of fresh fruits, vegetables, and spices from the region.', 'en', 'f0009', 'flores-200', 'daily_life', 1),
('Le marche etait plein de fruits frais, de legumes et d''epices de la region.', 'fr', 'f0009', 'flores-200', 'daily_life', 1),
('كان السوق مليئاً بالفواكه الطازجة والخضروات والتوابل من المنطقة.', 'ar', 'f0009', 'flores-200', 'daily_life', 1),
('Scientists have discovered a new species of fish in the depths of the ocean.', 'en', 'f0010', 'flores-200', 'science', 2),
('Les scientifiques ont decouvert une nouvelle espece de poisson dans les profondeurs de l''ocean.', 'fr', 'f0010', 'flores-200', 'science', 2),
('اكتشف العلماء نوعاً جديداً من الأسماك في أعماق المحيط.', 'ar', 'f0010', 'flores-200', 'science', 2),
('The old woman told stories to her grandchildren every evening under the stars.', 'en', 'f0011', 'flores-200', 'culture', 1),
('La vieille femme racontait des histoires a ses petits-enfants chaque soir sous les etoiles.', 'fr', 'f0011', 'flores-200', 'culture', 1),
('كانت المرأة العجوز تروي القصص لأحفادها كل مساء تحت النجوم.', 'ar', 'f0011', 'flores-200', 'culture', 1),
('New technology allows farmers to monitor their crops using mobile phones.', 'en', 'f0012', 'flores-200', 'technology', 2),
('La nouvelle technologie permet aux agriculteurs de surveiller leurs cultures avec des telephones.', 'fr', 'f0012', 'flores-200', 'technology', 2),
('تتيح التكنولوجيا الجديدة للمزارعين مراقبة محاصيلهم باستخدام الهواتف المحمولة.', 'ar', 'f0012', 'flores-200', 'technology', 2),
('The fishermen returned to the village at dawn with a large catch of fish.', 'en', 'f0013', 'flores-200', 'daily_life', 1),
('Les pecheurs sont rentres au village a l''aube avec une grande prise de poissons.', 'fr', 'f0013', 'flores-200', 'daily_life', 1),
('عاد الصيادون إلى القرية عند الفجر بصيد كبير من الأسماك.', 'ar', 'f0013', 'flores-200', 'daily_life', 1),
('The university opened a new research center for renewable energy.', 'en', 'f0014', 'flores-200', 'education', 2),
('L''universite a ouvert un nouveau centre de recherche sur les energies renouvelables.', 'fr', 'f0014', 'flores-200', 'education', 2),
('افتتحت الجامعة مركز أبحاث جديداً لدراسات الطاقة المتجددة.', 'ar', 'f0014', 'flores-200', 'education', 2),
('The camel caravan crossed the desert in three days despite the sandstorm.', 'en', 'f0015', 'flores-200', 'culture', 2),
('La caravane de chameaux a traverse le desert en trois jours malgre la tempete de sable.', 'fr', 'f0015', 'flores-200', 'culture', 2),
('عبرت قافلة الإبل الصحراء في ثلاثة أيام على الرغم من العاصفة الرملية.', 'ar', 'f0015', 'flores-200', 'culture', 2),
('The price of basic goods has increased significantly due to inflation.', 'en', 'f0016', 'flores-200', 'economy', 2),
('Le prix des produits de base a considerablement augmente en raison de l''inflation.', 'fr', 'f0016', 'flores-200', 'economy', 2),
('ارتفعت أسعار السلع الأساسية بشكل كبير بسبب التضخم.', 'ar', 'f0016', 'flores-200', 'economy', 2),
('The mother breastfed her baby while sitting under the shade of a large tree.', 'en', 'f0017', 'flores-200', 'health', 1),
('La mere allaitait son bebe assise a l''ombre d''un grand arbre.', 'fr', 'f0017', 'flores-200', 'health', 1),
('أرضعت الأم طفلها وهي جالسة تحت ظل شجرة كبيرة.', 'ar', 'f0017', 'flores-200', 'health', 1),
('The young man traveled to the capital city to find work and support his family.', 'en', 'f0018', 'flores-200', 'daily_life', 1),
('Le jeune homme a voyage vers la capitale pour trouver du travail et subvenir aux besoins de sa famille.', 'fr', 'f0018', 'flores-200', 'daily_life', 1),
('سافر الشاب إلى العاصمة للبحث عن عمل وإعالة أسرته.', 'ar', 'f0018', 'flores-200', 'daily_life', 1),
('Students organized a competition to promote reading in local languages.', 'en', 'f0019', 'flores-200', 'education', 2),
('Les etudiants ont organise un concours pour promouvoir la lecture dans les langues locales.', 'fr', 'f0019', 'flores-200', 'education', 2),
('نظم الطلاب مسابقة لتعزيز القراءة والكتابة باللغات المحلية.', 'ar', 'f0019', 'flores-200', 'education', 2),
('The mosque was beautifully decorated during the celebration of Ramadan.', 'en', 'f0020', 'flores-200', 'culture', 1),
('La mosquee etait magnifiquement decoree pendant la celebration du Ramadan.', 'fr', 'f0020', 'flores-200', 'culture', 1),
('كان المسجد مزيناً بشكل جميل خلال الاحتفال بشهر رمضان المبارك.', 'ar', 'f0020', 'flores-200', 'culture', 1);
